const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const repo=path.resolve(__dirname,'..');
(async()=>{
 const server=http.createServer((req,res)=>{let name=new URL(req.url,'http://localhost').pathname;if(name.endsWith('/'))name+='index.html';try{const f=path.join(repo,name);res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.html')?'text/html':'application/json');res.end(fs.readFileSync(f));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(8780,'127.0.0.1',r));
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox','--disable-gpu','--no-zygote']});const page=await browser.newPage({serviceWorkers:'block'});await page.route('https://cdn.jsdelivr.net/**',r=>r.fulfill({body:''}));await page.goto('http://127.0.0.1:8780/');await page.locator('[data-section="fortuneSection"]').click();await page.locator('#tc2FiveLevel').selectOption('adult');
 await page.evaluate(()=>{callOpenAiJson=async()=>({words:['gallery','admission','exhibition','sculpture','souvenir'].map(word=>({word,meaning:'意味',pos:'noun',note:'メモ'})),sentence:'A gallery exhibition features sculpture, admission and a souvenir.',translation:'ギャラリーの展示です。'});});await page.locator('#tc2FiveGenerate').click();await page.waitForFunction(()=>document.querySelectorAll('.tc2-word').length===5);const set=await page.locator('#tc2FiveResult').getAttribute('data-set-id');
 await page.locator('.tc2-word').nth(0).click();await page.waitForFunction(()=>document.getElementById('meaning').value.length>0);assert(await page.locator('#addSection').isVisible());assert.equal(await page.evaluate(()=>loadWords().length),0);await page.locator('#saveBtn').click();await page.waitForFunction(()=>document.getElementById('fortuneSection').classList.contains('active'));assert.equal(await page.evaluate(()=>loadWords().length),1);assert.equal(await page.locator('#tc2FiveResult').getAttribute('data-set-id'),set);await page.waitForFunction(()=>document.querySelector('.tc2-word[data-index="0"]').dataset.registered==='1');
 await page.locator('.tc2-word').nth(1).click();await page.waitForFunction(()=>document.getElementById('meaning').value.length>0);await page.locator('#meaning').fill('');await page.locator('#saveBtn').click();await page.waitForFunction(()=>!document.getElementById('saveBtn').disabled);assert(await page.locator('#addSection').isVisible());assert.equal(await page.evaluate(()=>loadWords().length),1);await page.locator('#meaning').fill('入場');await page.evaluate(()=>{window.realSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='tangoChoWords')throw new DOMException('Full','QuotaExceededError');return realSetItem.call(this,k,v);};});await page.locator('#saveBtn').click();await page.waitForFunction(()=>!document.getElementById('saveBtn').disabled);assert(await page.locator('#addSection').isVisible());assert.equal(await page.locator('#word').inputValue(),'admission');assert.equal(await page.evaluate(()=>loadWords().length),1);await page.evaluate(()=>{Storage.prototype.setItem=realSetItem;});await page.locator('#saveBtn').click();await page.waitForFunction(()=>document.getElementById('fortuneSection').classList.contains('active'));assert.equal(await page.evaluate(()=>loadWords().length),2);
 await page.locator('.tc2-word').nth(2).click();await page.waitForFunction(()=>document.getElementById('meaning').value.length>0);await page.locator('#clearBtn').click();await page.locator('#word').fill('independent');await page.locator('#meaning').fill('独立した');await page.locator('#saveBtn').click();await page.waitForFunction(()=>!document.getElementById('saveBtn').disabled);assert(await page.locator('#addSection').isVisible());assert.equal(await page.evaluate(()=>loadWords().length),3);
 await page.locator('[data-section="fortuneSection"]').click();await page.locator('.tc2-word').nth(3).click();await page.waitForFunction(()=>document.getElementById('meaning').value.length>0);await page.locator('[data-section="listSection"]').click();await page.locator('[data-section="addSection"]').click();await page.locator('#saveBtn').click();await page.waitForFunction(()=>!document.getElementById('saveBtn').disabled);assert(await page.locator('#addSection').isVisible());assert.equal(await page.evaluate(()=>loadWords().length),4);
 console.log('PASS: successful 5 WORDS registration returns to same set with registered mark; validation/quota failure preserves form; retry returns; cleared or navigated-away flow does not redirect normal save');await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
