const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const repo=path.resolve(__dirname,'..');
(async()=>{
 const server=http.createServer((req,res)=>{let name=new URL(req.url,'http://localhost').pathname;if(name.endsWith('/'))name+='index.html';try{const f=path.join(repo,name);res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.html')?'text/html':'application/json');res.end(fs.readFileSync(f));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(8782,'127.0.0.1',r));
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox','--disable-gpu','--no-zygote']});const context=await browser.newContext({serviceWorkers:'block'});const page=await context.newPage();await page.route('https://cdn.jsdelivr.net/**',r=>r.fulfill({body:''}));await page.clock.install();await page.goto('http://127.0.0.1:8782/');await page.waitForFunction(()=>!document.documentElement.hasAttribute('data-tc2-boot'));await page.locator('#tc2StudyTotal').waitFor();await page.bringToFront();await page.clock.pauseAt(new Date(Date.now()+1000));await page.clock.runFor(20000);assert.equal(await page.locator('#tc2StudyTotal').innerText(),'0分00秒');
 await page.locator('[data-section="fortuneSection"]').click();await page.clock.runFor(10000);assert.equal(await page.locator('#tc2StudyTotal').innerText(),'0分10秒');await page.clock.runFor(80000);assert.equal(await page.locator('#tc2StudyTotal').innerText(),'1分00秒');assert.equal(await page.locator('#tc2StudyState').innerText(),'停止中');await page.locator('[data-section="part5Section"]').click();await page.clock.runFor(10000);assert.equal(await page.locator('#tc2StudyTotal').innerText(),'1分10秒');
 await page.evaluate(()=>{window.visibility='hidden';Object.defineProperty(document,'visibilityState',{get:()=>visibility,configurable:true});document.dispatchEvent(new Event('visibilitychange'));});await page.clock.runFor(120000);assert.equal(await page.locator('#tc2StudyTotal').innerText(),'1分10秒');await page.evaluate(()=>{visibility='visible';document.dispatchEvent(new Event('visibilitychange'));});await page.clock.runFor(20000);assert.equal(await page.locator('#tc2StudyTotal').innerText(),'1分10秒');await page.locator('[data-section="quizSection"]').click();await page.clock.runFor(5000);assert.equal(await page.locator('#tc2StudyTotal').innerText(),'1分15秒');await page.clock.fastForward(3600000);assert.equal(await page.locator('#tc2StudyTotal').innerText(),'1分15秒');
 await page.locator('[data-section="addSection"]').click();await page.locator('#connSettingsCard summary').click();await page.clock.runFor(20000);assert.equal(await page.locator('#tc2StudyTotal').innerText(),'1分15秒');const downloads=page.waitForEvent('download');await page.locator('#exportJsonBtn').click();const download=await downloads;const data=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(data.studyTime.totalMs,75000);assert.equal(await page.evaluate(()=>loadWords().length),0);await page.clock.resume();await page.reload();await page.waitForFunction(()=>!document.documentElement.hasAttribute('data-tc2-boot'));assert.equal(await page.locator('#tc2StudyTotal').innerText(),'1分15秒');
 await page.locator('#connSettingsCard summary').click();page.once('dialog',dialog=>dialog.accept());await Promise.all([page.waitForEvent('load'),page.locator('#importJsonInput').setInputFiles({name:'time.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...data,studyTime:{totalMs:120000}}))})]);await page.waitForFunction(()=>!document.documentElement.hasAttribute('data-tc2-boot'));assert.equal(await page.locator('#tc2StudyTotal').innerText(),'2分00秒');
 await page.locator('#connSettingsCard summary').click();page.once('dialog',dialog=>dialog.accept());await Promise.all([page.waitForEvent('load'),page.locator('#importJsonInput').setInputFiles({name:'legacy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify([{word:'legacy',meaning:'昔'}]))})]);await page.waitForFunction(()=>!document.documentElement.hasAttribute('data-tc2-boot'));assert.equal(await page.locator('#tc2StudyTotal').innerText(),'2分00秒');assert.equal(await page.evaluate(()=>loadWords()[0].word),'legacy');
 console.log('PASS: no time on opening, active input increments, idle cutoff, hidden time excluded, visible return does not restart, all study tabs count, sleep excluded, settings paused, JSON export and reload preserve 75 seconds, JSON restores 120 seconds, legacy import preserves time');await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
